export const SET_MOST_RECENT_IN_PROGRESS = "SET_MOST_RECENT_IN_PROGRESS";
export const SET_MOST_VIEWED_IN_PROGRESS = "SET_MOST_VIEWED_IN_PROGRESS";
export const SET_MOST_LIKED_IN_PROGRESS = "SET_MOST_LIKED_IN_PROGRESS";
export const SET_MOST_RATED_IN_PROGRESS = "SET_MOST_RATED_IN_PROGRESS";
export const SET_MOST_RECENT = "SET_MOST_RECENT";
export const SET_MOST_VIEWED = "SET_MOST_VIEWED";
export const SET_MOST_LIKED = "SET_MOST_LIKED";
export const SET_MOST_RATED = "SET_MOST_RATED";
