export const SET_SEARCH_MODE = "SET_SEARCH_MODE";
export const SET_SEARCH_TEXT = "SET_SEARCH_TEXT";
export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";
export const SET_SEARCH_ERROR = "SET_SEARCH_ERROR";
